apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xm4k5okzd-go
  janus-idp.io/tekton: xm4k5okzd-go
  backstage.io/kubernetes-id: xm4k5okzd-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xm4k5okzd-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
